# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.4
  hooks:
  # Run the linter.
  - id: ruff
    types_or: [ python, pyi ]
    args: [ --fix ]
  # Run the formatter.
  - id: ruff-format
    types_or: [ python, pyi ]